package com.zte.mybatis.pojo;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class SmbsUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_USER.ID
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_USER.USERCODE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private String usercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_USER.USERNAME
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_USER.USERPASSWORD
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private String userpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_USER.GENDER
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private Long gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_USER.BIRTHDAY
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_USER.PHONE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_USER.ADDRESS
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_USER.USERROLE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private BigDecimal userrole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_USER.CREATEDBY
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private BigDecimal createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_USER.CREATIONDATE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_USER.MODIFYBY
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private BigDecimal modifyby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_USER.MODIFYDATE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private Date modifydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_USER.ID
     *
     * @return the value of SMBMS_USER.ID
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_USER.ID
     *
     * @param id the value for SMBMS_USER.ID
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_USER.USERCODE
     *
     * @return the value of SMBMS_USER.USERCODE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_USER.USERCODE
     *
     * @param usercode the value for SMBMS_USER.USERCODE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode == null ? null : usercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_USER.USERNAME
     *
     * @return the value of SMBMS_USER.USERNAME
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_USER.USERNAME
     *
     * @param username the value for SMBMS_USER.USERNAME
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_USER.USERPASSWORD
     *
     * @return the value of SMBMS_USER.USERPASSWORD
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_USER.USERPASSWORD
     *
     * @param userpassword the value for SMBMS_USER.USERPASSWORD
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword == null ? null : userpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_USER.GENDER
     *
     * @return the value of SMBMS_USER.GENDER
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public Long getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_USER.GENDER
     *
     * @param gender the value for SMBMS_USER.GENDER
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setGender(Long gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_USER.BIRTHDAY
     *
     * @return the value of SMBMS_USER.BIRTHDAY
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_USER.BIRTHDAY
     *
     * @param birthday the value for SMBMS_USER.BIRTHDAY
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_USER.PHONE
     *
     * @return the value of SMBMS_USER.PHONE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_USER.PHONE
     *
     * @param phone the value for SMBMS_USER.PHONE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_USER.ADDRESS
     *
     * @return the value of SMBMS_USER.ADDRESS
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_USER.ADDRESS
     *
     * @param address the value for SMBMS_USER.ADDRESS
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_USER.USERROLE
     *
     * @return the value of SMBMS_USER.USERROLE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public BigDecimal getUserrole() {
        return userrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_USER.USERROLE
     *
     * @param userrole the value for SMBMS_USER.USERROLE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setUserrole(BigDecimal userrole) {
        this.userrole = userrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_USER.CREATEDBY
     *
     * @return the value of SMBMS_USER.CREATEDBY
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public BigDecimal getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_USER.CREATEDBY
     *
     * @param createdby the value for SMBMS_USER.CREATEDBY
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setCreatedby(BigDecimal createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_USER.CREATIONDATE
     *
     * @return the value of SMBMS_USER.CREATIONDATE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_USER.CREATIONDATE
     *
     * @param creationdate the value for SMBMS_USER.CREATIONDATE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_USER.MODIFYBY
     *
     * @return the value of SMBMS_USER.MODIFYBY
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public BigDecimal getModifyby() {
        return modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_USER.MODIFYBY
     *
     * @param modifyby the value for SMBMS_USER.MODIFYBY
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setModifyby(BigDecimal modifyby) {
        this.modifyby = modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_USER.MODIFYDATE
     *
     * @return the value of SMBMS_USER.MODIFYDATE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_USER.MODIFYDATE
     *
     * @param modifydate the value for SMBMS_USER.MODIFYDATE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    public SmbsUser(BigDecimal id, String usercode, String username) {
        this.id = id;
        this.usercode = usercode;
        this.username = username;
    }

    public SmbsUser(Long gender) {
        this.gender = gender;
    }
}