package com.zte.mybatis.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class SmbsAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_ADDRESS.ID
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_ADDRESS.CONTACT
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_ADDRESS.ADDRESSDESC
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private String addressdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_ADDRESS.POSTCODE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_ADDRESS.TEL
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_ADDRESS.CREATEDBY
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private BigDecimal createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_ADDRESS.CREATIONDATE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_ADDRESS.MODIFYBY
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private BigDecimal modifyby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_ADDRESS.MODIFYDATE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMBMS_ADDRESS.USERID
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    private BigDecimal userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_ADDRESS.ID
     *
     * @return the value of SMBMS_ADDRESS.ID
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_ADDRESS.ID
     *
     * @param id the value for SMBMS_ADDRESS.ID
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_ADDRESS.CONTACT
     *
     * @return the value of SMBMS_ADDRESS.CONTACT
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_ADDRESS.CONTACT
     *
     * @param contact the value for SMBMS_ADDRESS.CONTACT
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_ADDRESS.ADDRESSDESC
     *
     * @return the value of SMBMS_ADDRESS.ADDRESSDESC
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public String getAddressdesc() {
        return addressdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_ADDRESS.ADDRESSDESC
     *
     * @param addressdesc the value for SMBMS_ADDRESS.ADDRESSDESC
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setAddressdesc(String addressdesc) {
        this.addressdesc = addressdesc == null ? null : addressdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_ADDRESS.POSTCODE
     *
     * @return the value of SMBMS_ADDRESS.POSTCODE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_ADDRESS.POSTCODE
     *
     * @param postcode the value for SMBMS_ADDRESS.POSTCODE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_ADDRESS.TEL
     *
     * @return the value of SMBMS_ADDRESS.TEL
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_ADDRESS.TEL
     *
     * @param tel the value for SMBMS_ADDRESS.TEL
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_ADDRESS.CREATEDBY
     *
     * @return the value of SMBMS_ADDRESS.CREATEDBY
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public BigDecimal getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_ADDRESS.CREATEDBY
     *
     * @param createdby the value for SMBMS_ADDRESS.CREATEDBY
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setCreatedby(BigDecimal createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_ADDRESS.CREATIONDATE
     *
     * @return the value of SMBMS_ADDRESS.CREATIONDATE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_ADDRESS.CREATIONDATE
     *
     * @param creationdate the value for SMBMS_ADDRESS.CREATIONDATE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_ADDRESS.MODIFYBY
     *
     * @return the value of SMBMS_ADDRESS.MODIFYBY
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public BigDecimal getModifyby() {
        return modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_ADDRESS.MODIFYBY
     *
     * @param modifyby the value for SMBMS_ADDRESS.MODIFYBY
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setModifyby(BigDecimal modifyby) {
        this.modifyby = modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_ADDRESS.MODIFYDATE
     *
     * @return the value of SMBMS_ADDRESS.MODIFYDATE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_ADDRESS.MODIFYDATE
     *
     * @param modifydate the value for SMBMS_ADDRESS.MODIFYDATE
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMBMS_ADDRESS.USERID
     *
     * @return the value of SMBMS_ADDRESS.USERID
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public BigDecimal getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMBMS_ADDRESS.USERID
     *
     * @param userid the value for SMBMS_ADDRESS.USERID
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    public void setUserid(BigDecimal userid) {
        this.userid = userid;
    }
}