package com.zte.mybatis.mapper;

import com.zte.mybatis.pojo.SmbsAddress;
import com.zte.mybatis.pojo.SmbsAddressExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmbsAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_ADDRESS
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    int countByExample(SmbsAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_ADDRESS
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    int deleteByExample(SmbsAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_ADDRESS
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_ADDRESS
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    int insert(SmbsAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_ADDRESS
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    int insertSelective(SmbsAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_ADDRESS
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    List<SmbsAddress> selectByExample(SmbsAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_ADDRESS
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    SmbsAddress selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_ADDRESS
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    int updateByExampleSelective(@Param("record") SmbsAddress record, @Param("example") SmbsAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_ADDRESS
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    int updateByExample(@Param("record") SmbsAddress record, @Param("example") SmbsAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_ADDRESS
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(SmbsAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_ADDRESS
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    int updateByPrimaryKey(SmbsAddress record);
}