package com.zte.mybatis.mapper;

import com.zte.mybatis.pojo.SmbsUser;
import com.zte.mybatis.pojo.SmbsUserExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmbsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_USER
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    int countByExample(SmbsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_USER
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    int deleteByExample(SmbsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_USER
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_USER
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    int insert(SmbsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_USER
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    int insertSelective(SmbsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_USER
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    List<SmbsUser> selectByExample(SmbsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_USER
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    SmbsUser selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_USER
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    int updateByExampleSelective(@Param("record") SmbsUser record, @Param("example") SmbsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_USER
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    int updateByExample(@Param("record") SmbsUser record, @Param("example") SmbsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_USER
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(SmbsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMBMS_USER
     *
     * @mbggenerated Tue Sep 06 16:20:30 GMT+08:00 2022
     */
    int updateByPrimaryKey(SmbsUser record);
}